# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f88723175efee5a84ee5f4c1d5af2ad240a825d53db13d95fa3522cef54a89db278ec6d80fb9aa4ef6eb27207531b557c117847edcf8ef2d25b6429d304677

test:
  secret_key_base: 5b5605accc7d516bc5a979590d6d6f30301c8379ce9ea4d8aff13eba24cfc8f77bfd04e65e7e672f76a8a297b2d904300b9053a529cb3a4977996a8a0fdffe53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
